name: edgehead
version: 2.0.1
description: A game of fractal stories.
homepage: https://www.egamebook.com
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.3.0
  built_collection: ^5.1.1
  built_value: ^8.1.3
  cli_menu: ^0.4.0+1
  collection: ^1.15.0
  egamebook_builder:
    path: ../egamebook_builder
  logging: ^1.0.2
  meta: ^1.1.8
  path: ^1.6.2
  quiver: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.4
  built_value_generator: ^8.1.3
  lint: ^2.3.0
  t_stats: ^3.0.0
  test: ^1.15.3
