name: egamebook_builder
description: Builders for egamebook.
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: '>=6.4.1 <6.5.0'
  build: ^2.1.1
  code_builder: ^4.1.0
  dart_style: ^2.2.0
  glob: ^2.0.2
  source_gen: ^1.1.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  meta: ^1.1.8
  test: ^1.15.3