name: egamebook_builder
description: Builders for egamebook.
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.4 <0.37.0'
  build: ^1.0.0
  code_builder: ^3.1.2
  dart_style: ^1.1.3
  glob: ^1.1.7
  source_gen: ^0.9.0

dev_dependencies:
  test: ^1.0.0
