name: egamebook_builder
description: Builders for egamebook.
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.39.16 <0.40.0'
  build: ^1.0.0
  code_builder: ^3.1.2
  dart_style: ^1.3.6
  glob: ^1.1.7
  source_gen: ^0.9.6

dev_dependencies:
  meta: ^1.1.8
  test: ^1.15.3